config/routes.rb
BetterReddit::Application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :links do
    member do
      post :upvote, to: "votes#upvote_link"
      post :downvote, to: "votes#downvote_link"
      post :unvote, to: "votes#unvote_link"
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy] do
    member do
      post :upvote, to: "votes#upvote_comment"
      post :downvote, to: "votes#downvote_comment"
    end
  end
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  url            :string(255)
#  body           :string(255)
#  user_id        :integer
#  created_at     :datetime
#  updated_at     :datetime
#  upvote_count   :integer
#  downvote_count :integer
#

class Link < ActiveRecord::Base
  belongs_to :user
  has_many :link_subs
  has_many :subs, through: :link_subs, source: :sub
  has_many :comments
  has_many :votes

  validates :title, :url, :user_id, presence: true

  def comments_by_parent_id
    return @hash if @hash
    @hash = Hash.new { |h, k| h[k] = [] }
    self.comments.each do |comment|
      @hash[comment.parent_comment_id] << comment
    end
    @hash
  end

  def score
    self.votes.pluck(:vote).inject(:+) || 0
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # before_action :check_logged_in, only: [:create, :check_if_op]
  before_action :check_if_op, only: [:edit, :update, :destroy]

  def create
    @link = current_user.links.new(link_params)

    if @link.save
      redirect_to link_url(@link)
    else
      flash[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
    render :edit
  end

  def new
    @link = Link.new
    render :new
  end

  def show
    @link = Link.find(params[:id])
    @comments = @link.comments
    render :show
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(link_params)
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to :back
  end

  private

    def link_params
      params.require(:link).permit(:title, :url, :body, sub_ids: [])
    end

    def check_if_op
      @link =  Link.find(params[:id])
      unless @link.user_id == current_user.id
        redirect_to link_url(@link)
      end
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_comment.html.erb
<%= comment.user.username %> said <%= distance_of_time_in_words(Time.now - comment.created_at) %> ago:<br>
<div class="comment">
  <%= comment.body %>
</div>
<br>
Reply to <%= comment.user.username %>:
<%= render 'comment_form', parent_id: comment.id %>

<blockquote>
  <% comments_by_parent_id[comment.id].each do |child| %>
    <%= render 'comment', comment: child, comments_by_parent_id: comments_by_parent_id %>
  <% end %>
</blockquote>

app/views/links/_comment_form.html.erb
<form action="<%= link_comments_url(@link) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= parent_id %>">

  <label type="hidden" for="body" value="reply"></label>
  <textarea id="body" name="comment[body]"></textarea>

  <br><button>Reply</button>
</form>

app/views/links/_votes.html.erb
<% if current_user.upvoted?(link) %>
  <% top_action, bottom_action = unvote_link_url(link), downvote_link_url(link) %>
  <% up_class = 'up' %>
<% elsif current_user.downvoted?(link) %>
  <% top_action, bottom_action = upvote_link_url(link), unvote_link_url(link) %>
  <% down_class = 'down' %>
<% else %>
  <% top_action, bottom_action = upvote_link_url(link), downvote_link_url(link) %>
<% end %>

<div class="arrows link">
  <form action="<%= top_action %>" method="post">
    <div class="arrow">
      <input type="submit" value="<%= like %>" class="<%= up_class %>"/>
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    </div>
  </form>

  <div class="score"><%= link.score %></div>

  <form action="<%= bottom_action %>" method="post">
    <div class="arrow"><input type="submit" value="<%= dislike %>" class="<%= down_class %>"/>
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    </div>
  </form>
</div>

app/views/links/edit.html.erb
Edit Link

<form action="<%= link_url(@link) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="PATCH">

  <label>Title:
    <input type="text" name="link[title]" value="<%= @link.title %>">
  </label>
  <label>URL:
    <input type="text" name="link[url]" value="<%= @link.url %>">
  </label>
  <label>Body:
    <input type="text" name="link[body]" value="<%= @link.body %>">
  </label>

  <input type="hidden" name="link[sub_ids][]" value="">


  <% Sub.all.each do |sub| %>
  <label>
    <input type="checkbox" name="link[sub_ids][]" value="<%= sub.id %>"
    <%= "checked" if @link.subs.pluck(:id).include?(sub.id) %>>

    <%= sub.name %>
  </label>
  <% end %>

  <button>Update Link</button>
</form>

app/views/links/new.html.erb
New Link
<form action="<%= links_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title:
    <input type="text" name="link[title]" value="<%= @link.title %>">
  </label>
  <label>URL:
    <input type="text" name="link[url]" value="<%= @link.url %>">
  </label>
  <label>Body:
    <input type="text" name="link[body]" value="<%= @link.body %>">
  </label>

  <% Sub.all.each do |sub| %>
  <label>
    <input type="checkbox" name="link[sub_ids][]" value="<%= sub.id %>">
    <%= sub.name %>
  </label>
  <% end %>

  <button>Create New Link</button>
</form>

app/views/links/show.html.erb
<div class="link-title">
  <%= render 'votes', link: @link %>
  <div class="link">
    <h1><%= @link.title %></h1>
  </div>
</div>
<%= link_to @link.url, @link.url %>
<br>

<%= @link.body %>
<br>

In subs: <% @link.subs.each do |sub| %>
  <%= link_to sub.name, sub_url(sub) %>
<% end %>
<br><br>

<% if current_user.id == @link.user_id %>
  <%= link_to "Edit Link", edit_link_url(@link) %>
<% end %>
<br><br>


<h4>Leave a comment:</h4>
<%= render 'comment_form', parent_id: nil %>
<br>
<h2>Comments:</h2>
<% comments_hash = @link.comments_by_parent_id %>
<% comments_hash[nil].each do |comment| %>
  <%= render 'comment', comment: comment, comments_by_parent_id: comments_hash %>
<% end %>