config/routes.rb
BetterReddit::Application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :links do
    member do
      post :upvote, to: "votes#upvote_link"
      post :downvote, to: "votes#downvote_link"
      post :unvote, to: "votes#unvote_link"
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy] do
    member do
      post :upvote, to: "votes#upvote_comment"
      post :downvote, to: "votes#downvote_comment"
    end
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Sub < ActiveRecord::Base
  validates :name, :user_id, :presence => true
  has_many :link_subs, inverse_of: :sub
  has_many :links, through: :link_subs, source: :link

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :check_if_op, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    links = @sub.links.new(link_params)
    links.each { |link| link.user_id = current_user.id }
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def destroy
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:name)
  end

  def link_params
    params.permit(:links => [:title, :url, :body]).require(:links).values
          .reject { |data| data.values.all?(&:blank?) }
  end

  def check_if_op
    @link =  Link.find(params[:id])
    unless @link.user_id == current_user.id
      redirect_to link_url(@link)
    end
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
Edit Sub

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label>Name
    <input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label>


<button>Update Sub</button>
</form>

app/views/subs/index.html.erb
Subs Index

<ul>
  <% @subs.each do |sub| %>
    <li>
      <%= link_to sub.name, sub_url(sub) %>
    </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
New Sub Page

<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Name
    <input type="text" name="sub[name]" value="<%= @sub.name %>">
  </label>

  <% 5.times do |i| %>
    <fieldset>
      <label>Title:
        <input type="text" name="links[<%= i + 1 %>][title]" value="">
      </label>
      <label>URL:
        <input type="text" name="links[<%= i + 1 %>][url]" value="">
      </label>
      <label>Body:
        <input type="text" name="links[<%= i + 1 %>][body]" value="">
      </label>
    </fieldset>
  <% end %>

  <button>Create New Sub</button>
</form>

app/views/subs/show.html.erb
<%= @sub.name %>
<ul>
<% @sub.links.each do |link| %>
  <li>
    <%= link_to link.title, link_url(link) %>
    <%= link_to link.url, link.url.to_s %>
    <%= link.body %>
    <%= button_to "Remove Link", link_url(link), method: :delete %>
  </li>
<% end %>
</ul>